server:
  port: 8080
spring:
  application:
    name: my-code-generator
  datasource:
    url: jdbc:mysql://localhost:3306/aiwo_plat_item?useUnicode=true&characterEncoding=UTF-8&useAffectedRows=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: root